import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { siteName, files } = await request.json();
    
    // Get Netlify token from cookie
    const netlifyToken = request.cookies.get('netlify_token')?.value;
    
    if (!netlifyToken) {
      return NextResponse.json({ 
        error: 'Not authenticated with Netlify. Please connect your Netlify account first.' 
      }, { status: 401 });
    }
    
    if (!files || Object.keys(files).length === 0) {
      return NextResponse.json({ 
        error: 'No files to deploy' 
      }, { status: 400 });
    }
    
    console.log('[netlify-deploy] Starting deployment...');
    console.log('[netlify-deploy] Site name:', siteName);
    console.log('[netlify-deploy] Files count:', Object.keys(files).length);
    
    // Get user's sites
    const sitesResponse = await fetch('https://api.netlify.com/api/v1/sites', {
      headers: {
        'Authorization': `Bearer ${netlifyToken}`,
      },
    });
    
    if (!sitesResponse.ok) {
      throw new Error('Failed to fetch Netlify sites');
    }
    
    const sites = await sitesResponse.json();
    let siteId = null;
    
    // Check if site exists
    const existingSite = sites.find((site: any) => site.name === siteName);
    
    if (existingSite) {
      siteId = existingSite.id;
      console.log('[netlify-deploy] Found existing site:', siteId);
    } else {
      // Create new site
      console.log('[netlify-deploy] Creating new site...');
      const createSiteResponse = await fetch('https://api.netlify.com/api/v1/sites', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${netlifyToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: siteName,
        }),
      });
      
      if (!createSiteResponse.ok) {
        const errorText = await createSiteResponse.text();
        console.error('[netlify-deploy] Failed to create site:', errorText);
        throw new Error('Failed to create Netlify site');
      }
      
      const newSite = await createSiteResponse.json();
      siteId = newSite.id;
      console.log('[netlify-deploy] Created new site:', siteId);
    }
    
    // Prepare files for deployment
    const deployFiles: { [key: string]: string } = {};
    
    console.log('[netlify-deploy] Processing files...');
    console.log('[netlify-deploy] Input files:', Object.keys(files));
    
    // Keep the file structure as is, just remove leading slashes
    for (const [path, content] of Object.entries(files)) {
      const cleanPath = path.replace(/^\/+/, '');
      deployFiles[cleanPath] = content as string;
      console.log('[netlify-deploy] Added file:', cleanPath);
    }
    
    // Ensure we have index.html at the root
    if (!deployFiles['index.html']) {
      console.log('[netlify-deploy] Creating index.html...');
      
      // Check if we have the files
      const hasAppJsx = deployFiles['src/App.jsx'] || deployFiles['App.jsx'];
      const hasMainJsx = deployFiles['src/main.jsx'] || deployFiles['main.jsx'];
      
      deployFiles['index.html'] = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My Awesome App</title>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { 
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        min-height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
      }
      #root { width: 100%; }
      .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 40px 20px;
        text-align: center;
      }
      h1 {
        color: white;
        font-size: 3rem;
        margin-bottom: 20px;
        text-shadow: 2px 2px 4px rgba(0,0,0,0.2);
      }
      p {
        color: rgba(255,255,255,0.9);
        font-size: 1.2rem;
        line-height: 1.6;
      }
      .code-preview {
        background: rgba(0,0,0,0.2);
        border-radius: 12px;
        padding: 20px;
        margin-top: 30px;
        backdrop-filter: blur(10px);
      }
      .file-list {
        text-align: left;
        color: rgba(255,255,255,0.8);
        font-family: 'Monaco', 'Courier New', monospace;
        font-size: 14px;
      }
      .badge {
        display: inline-block;
        background: rgba(255,255,255,0.2);
        padding: 8px 16px;
        border-radius: 20px;
        margin: 5px;
        color: white;
        font-size: 14px;
      }
    </style>
  </head>
  <body>
    <div id="root">
      <div class="container">
        <h1>🎉 Your App is Live!</h1>
        <p>This site was generated by Youssef AI and deployed to Netlify.</p>
        <div class="code-preview">
          <div class="file-list">
            <h3 style="color: white; margin-bottom: 15px;">📁 Deployed Files:</h3>
            ${Object.keys(deployFiles).map(f => `<div>📄 ${f}</div>`).join('')}
          </div>
        </div>
        <div style="margin-top: 30px;">
          ${hasAppJsx ? '<div class="badge">⚛️ React App</div>' : ''}
          ${hasMainJsx ? '<div class="badge">🚀 Vite Powered</div>' : ''}
          <div class="badge">✨ AI Generated</div>
        </div>
      </div>
    </div>
  </body>
</html>`;
    }
    
    console.log('[netlify-deploy] Final files to deploy:', Object.keys(deployFiles));
    
    // Create deployment
    const deployResponse = await fetch(`https://api.netlify.com/api/v1/sites/${siteId}/deploys`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${netlifyToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        files: deployFiles,
      }),
    });
    
    if (!deployResponse.ok) {
      const errorText = await deployResponse.text();
      console.error('[netlify-deploy] Deployment failed:', errorText);
      throw new Error('Failed to create deployment');
    }
    
    const deployment = await deployResponse.json();
    console.log('[netlify-deploy] Deployment created:', deployment.id);
    
    // Wait a bit for deployment to process
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    return NextResponse.json({
      success: true,
      deploymentId: deployment.id,
      siteId: siteId,
      url: deployment.deploy_ssl_url || deployment.url,
      adminUrl: deployment.admin_url,
    });
    
  } catch (error) {
    console.error('[netlify-deploy] Error:', error);
    return NextResponse.json({ 
      error: error instanceof Error ? error.message : 'Deployment failed' 
    }, { status: 500 });
  }
}
