import { NextRequest, NextResponse } from 'next/server';
import { createHash } from 'crypto';

// Helper function to create SHA1 hash
function createSHA1(content: string): string {
  return createHash('sha1').update(content).digest('hex');
}

export async function POST(request: NextRequest) {
  try {
    const { siteName, files, netlifyToken: bodyToken } = await request.json();
    
    // Get Netlify token
    const netlifyToken = bodyToken || request.headers.get('X-Netlify-Token') || request.cookies.get('netlify_token')?.value;
    
    if (!netlifyToken) {
      return NextResponse.json({ 
        error: 'Netlify token not provided. Please add your Netlify Personal Access Token in API Keys settings.' 
      }, { status: 401 });
    }
    
    if (!files || Object.keys(files).length === 0) {
      return NextResponse.json({ 
        error: 'No files to deploy' 
      }, { status: 400 });
    }
    
    console.log('[netlify] 🚀 Starting deployment...');
    console.log('[netlify] Site name:', siteName);
    console.log('[netlify] Files:', Object.keys(files).length);
    
    // Step 1: Get or create site
    console.log('[netlify] 📡 Checking for existing site...');
    const sitesResponse = await fetch('https://api.netlify.com/api/v1/sites', {
      headers: { 'Authorization': `Bearer ${netlifyToken}` },
    });
    
    if (!sitesResponse.ok) {
      throw new Error('Failed to authenticate with Netlify. Check your token.');
    }
    
    const sites = await sitesResponse.json();
    const existingSite = sites.find((site: any) => site.name === siteName);
    
    let siteId: string;
    let siteUrl: string;
    
    if (existingSite) {
      siteId = existingSite.id;
      siteUrl = existingSite.ssl_url || existingSite.url;
      console.log('[netlify] ✅ Using existing site:', siteId);
    } else {
      console.log('[netlify] 🏗️ Creating new site...');
      const createResponse = await fetch('https://api.netlify.com/api/v1/sites', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${netlifyToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ name: siteName }),
      });
      
      if (!createResponse.ok) {
        const errorText = await createResponse.text();
        throw new Error(`Failed to create site: ${errorText}`);
      }
      
      const newSite = await createResponse.json();
      siteId = newSite.id;
      siteUrl = newSite.ssl_url || newSite.url;
      console.log('[netlify] ✅ Created site:', siteId);
    }
    
    // Step 2: Prepare all files
    const deployFiles: Record<string, string> = {};
    
    console.log('[netlify] 📦 Processing files...');
    for (const [path, content] of Object.entries(files)) {
      const cleanPath = path.replace(/^\/+/, '');
      deployFiles[cleanPath] = content as string;
      console.log(`[netlify] ✓ ${cleanPath}`);
    }
    
    // Step 3: Ensure index.html exists
    if (!deployFiles['index.html']) {
      console.log('[netlify] 📝 Creating index.html...');
      deployFiles['index.html'] = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Created by Youssef AI</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: system-ui, -apple-system, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      padding: 20px;
    }
    .container {
      max-width: 800px;
      text-align: center;
      background: rgba(255, 255, 255, 0.1);
      padding: 60px 40px;
      border-radius: 20px;
      backdrop-filter: blur(10px);
      box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
    }
    h1 {
      font-size: 3rem;
      margin-bottom: 20px;
      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
    }
    p { font-size: 1.2rem; opacity: 0.9; margin-bottom: 30px; }
    .files {
      background: rgba(0, 0, 0, 0.2);
      padding: 20px;
      border-radius: 10px;
      margin-top: 30px;
      text-align: left;
      max-height: 300px;
      overflow-y: auto;
    }
    .file { padding: 5px 0; font-family: monospace; font-size: 14px; }
    .badge {
      display: inline-block;
      background: rgba(255, 255, 255, 0.2);
      padding: 8px 16px;
      border-radius: 20px;
      margin: 5px;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>🎉 Website Live!</h1>
    <p>This site was generated by Youssef AI and deployed to Netlify.</p>
    <div style="margin: 20px 0;">
      <span class="badge">✨ AI Generated</span>
      <span class="badge">🌐 Netlify</span>
      <span class="badge">🚀 Live Now</span>
    </div>
    <div class="files">
      <strong>📁 Deployed Files (${Object.keys(deployFiles).length}):</strong>
      ${Object.keys(deployFiles).map(f => `<div class="file">📄 ${f}</div>`).join('')}
    </div>
  </div>
</body>
</html>`;
    }
    
    // Step 4: Create file hashes and prepare for upload
    const fileHashes: Record<string, string> = {};
    for (const [path, content] of Object.entries(deployFiles)) {
      fileHashes[path] = createSHA1(content);
    }
    
    console.log('[netlify] 🎯 Creating deployment...');
    
    // Use the simpler deploy API - direct upload
    const formData = new FormData();
    
    // Create a zip-like structure by uploading all files
    const uploadPromises: Promise<any>[] = [];
    
    // First, create the deployment
    const deployResponse = await fetch(`https://api.netlify.com/api/v1/sites/${siteId}/deploys`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${netlifyToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        files: fileHashes,
        draft: false,
      }),
    });
    
    if (!deployResponse.ok) {
      const errorText = await deployResponse.text();
      throw new Error(`Deployment failed: ${errorText}`);
    }
    
    const deployment = await deployResponse.json();
    const deployId = deployment.id;
    const requiredFiles = deployment.required || Object.keys(deployFiles);
    
    console.log('[netlify] ✅ Deployment created:', deployId);
    console.log('[netlify] 📤 Uploading', requiredFiles.length, 'files...');
    
    // Upload all required files
    for (const filePath of requiredFiles) {
      const content = deployFiles[filePath];
      if (!content) continue;
      
      try {
        const uploadUrl = `https://api.netlify.com/api/v1/deploys/${deployId}/files/${encodeURIComponent(filePath)}`;
        const uploadResponse = await fetch(uploadUrl, {
          method: 'PUT',
          headers: {
            'Authorization': `Bearer ${netlifyToken}`,
            'Content-Type': 'application/octet-stream',
          },
          body: content,
        });
        
        if (uploadResponse.ok) {
          console.log(`[netlify] ✓ Uploaded: ${filePath}`);
        } else {
          console.error(`[netlify] ✗ Failed: ${filePath}`);
        }
      } catch (err) {
        console.error(`[netlify] ✗ Error uploading ${filePath}:`, err);
      }
    }
    
    console.log('[netlify] ✅ All files uploaded!');
    
    // Wait a bit for Netlify to process
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // Get final status
    const statusResponse = await fetch(`https://api.netlify.com/api/v1/deploys/${deployId}`, {
      headers: { 'Authorization': `Bearer ${netlifyToken}` },
    });
    
    const status = await statusResponse.json();
    const finalUrl = status.ssl_url || status.url || siteUrl;
    
    console.log('[netlify] 🎉 Deployment complete!');
    console.log('[netlify] 🌐 URL:', finalUrl);
    console.log('[netlify] 📊 Status:', status.state);
    
    return NextResponse.json({
      success: true,
      deploymentId: deployId,
      siteId: siteId,
      url: finalUrl,
      adminUrl: status.admin_url,
      state: status.state,
      message: `✅ Site deployed successfully! Visit: ${finalUrl}\n\n⏱️ If you see a 404, wait 30-60 seconds for Netlify to finish building.`
    });
    
  } catch (error: any) {
    console.error('[netlify] ❌ Error:', error);
    return NextResponse.json({ 
      error: error.message || 'Deployment failed',
      details: error.stack
    }, { status: 500 });
  }
}
