import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { projectName, files, vercelToken: bodyToken } = await request.json();
    
    // Get Vercel token
    const vercelToken = bodyToken || request.headers.get('X-Vercel-Token') || request.cookies.get('vercel_token')?.value;
    
    if (!vercelToken) {
      return NextResponse.json({ 
        error: 'Vercel token not provided. Please add your Vercel API Token in API Keys settings.' 
      }, { status: 401 });
    }
    
    if (!files || Object.keys(files).length === 0) {
      return NextResponse.json({ 
        error: 'No files to deploy' 
      }, { status: 400 });
    }
    
    console.log('[vercel] 🚀 Starting deployment...');
    console.log('[vercel] Project:', projectName);
    console.log('[vercel] Files:', Object.keys(files).length);
    
    // Prepare files for Vercel
    const deployFiles: Array<{ file: string; data: string }> = [];
    
    console.log('[vercel] 📦 Processing files...');
    for (const [path, content] of Object.entries(files)) {
      const cleanPath = path.replace(/^\/+/, '');
      deployFiles.push({
        file: cleanPath,
        data: content as string,
      });
      console.log(`[vercel] ✓ ${cleanPath}`);
    }
    
    // Check if this is a React/Vite app
    const isReactApp = deployFiles.some(f => 
      f.file === 'src/App.jsx' || f.file === 'src/main.jsx' ||
      f.file === 'src/App.tsx' || f.file === 'src/main.tsx'
    );
    
    // Ensure index.html exists
    const hasIndex = deployFiles.some(f => f.file === 'index.html');
    if (!hasIndex) {
      console.log('[vercel] 📝 Creating index.html...');
      
      let indexHtml;
      if (isReactApp) {
        // React/Vite index.html
        indexHtml = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Youssef AI Generated Site</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`;
      } else {
        // Static HTML
        indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Created by Youssef AI</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: system-ui, -apple-system, sans-serif;
      background: linear-gradient(135deg, #000000 0%, #434343 100%);
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      padding: 20px;
    }
    .container {
      max-width: 800px;
      text-align: center;
      background: rgba(255, 255, 255, 0.05);
      padding: 60px 40px;
      border-radius: 20px;
      backdrop-filter: blur(10px);
      border: 1px solid rgba(255, 255, 255, 0.1);
    }
    h1 {
      font-size: 3rem;
      margin-bottom: 20px;
      background: linear-gradient(135deg, #fff 0%, #999 100%);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
    }
    p { font-size: 1.2rem; opacity: 0.9; margin-bottom: 30px; }
    .files {
      background: rgba(0, 0, 0, 0.3);
      padding: 20px;
      border-radius: 10px;
      margin-top: 30px;
      text-align: left;
      max-height: 300px;
      overflow-y: auto;
    }
    .file { padding: 5px 0; font-family: monospace; font-size: 14px; }
    .badge {
      display: inline-block;
      background: rgba(255, 255, 255, 0.1);
      padding: 8px 16px;
      border-radius: 20px;
      margin: 5px;
      font-size: 14px;
      border: 1px solid rgba(255, 255, 255, 0.2);
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>▲ Deployed to Vercel</h1>
    <p>This site was generated by Youssef AI and deployed to Vercel.</p>
    <div style="margin: 20px 0;">
      <span class="badge">✨ AI Generated</span>
      <span class="badge">▲ Vercel</span>
      <span class="badge">🚀 Live Now</span>
    </div>
    <div class="files">
      <strong>📁 Deployed Files (${deployFiles.length}):</strong>
      ${deployFiles.map(f => `<div class="file">📄 ${f.file}</div>`).join('')}
    </div>
  </div>
</body>
</html>`;
      }
      deployFiles.push({
        file: 'index.html',
        data: indexHtml,
      });
    }
    
    // Add vercel.json for build configuration if React/Vite
    if (isReactApp && !deployFiles.some(f => f.file === 'vercel.json')) {
      console.log('[vercel] ⚙️ Creating vercel.json for React/Vite app...');
      deployFiles.push({
        file: 'vercel.json',
        data: JSON.stringify({
          "buildCommand": "npm install && npm run build",
          "outputDirectory": "dist",
          "devCommand": "npm run dev",
          "installCommand": "npm install",
          "framework": "vite",
          "rewrites": [
            { "source": "/(.*)", "destination": "/index.html" }
          ]
        }, null, 2)
      });
    }
    
    console.log('[vercel] 🎯 Creating deployment...');
    
    // Create deployment using Vercel API v2
    const deploymentBody = {
      name: projectName,
      files: deployFiles,
      projectSettings: {
        framework: null,
        buildCommand: null,
        outputDirectory: null,
      },
      target: 'production',
    };
    
    const deployResponse = await fetch('https://api.vercel.com/v13/deployments', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${vercelToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(deploymentBody),
    });
    
    if (!deployResponse.ok) {
      const errorText = await deployResponse.text();
      console.error('[vercel] Deploy failed:', errorText);
      throw new Error(`Vercel deployment failed: ${errorText}`);
    }
    
    const deployment = await deployResponse.json();
    
    console.log('[vercel] ✅ Deployment created!');
    console.log('[vercel] 🌐 URL:', deployment.url);
    
    // Construct full URL
    const deploymentUrl = `https://${deployment.url}`;
    
    console.log('[vercel] 🎉 Deployment complete!');
    console.log('[vercel] 📊 Status:', deployment.readyState);
    
    return NextResponse.json({
      success: true,
      deploymentId: deployment.id,
      url: deploymentUrl,
      inspectorUrl: deployment.inspectorUrl,
      readyState: deployment.readyState,
      message: `✅ Site deployed to Vercel! Visit: ${deploymentUrl}\n\n⏱️ Your site is building now and will be ready in 30-60 seconds.`
    });
    
  } catch (error: any) {
    console.error('[vercel] ❌ Error:', error);
    return NextResponse.json({ 
      error: error.message || 'Vercel deployment failed',
      details: error.stack
    }, { status: 500 });
  }
}
